/**
 * Created by vuchien on 7/27/16.
 */
export const STATE_HANDLING_CHANGE_PASSWORD = 'STATE_HANDLING_CHANGE_PASSWORD';
export const UPDATE_CHANGE_PASSWORD_STATUS = 'UPDATE_CHANGE_PASSWORD_STATUS';
export const UPDATE_CHANGE_PASSWORD_STATUS_TO_FALSE = 'UPDATE_CHANGE_PASSWORD_STATUS_TO_FALSE';
