/**
 * Created by vuchien on 6/18/16.
 */
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const FETCHING_CATEGORIES = 'FETCHING_CATEGORIES';
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';
export const SEARCH_RECEIVE = 'SEARCH_RECEIVE';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREV_PAGE = 'PREV_PAGE';
export const IS_ADDED_NEW_CATEGORY_TO_FALSE = 'IS_ADDED_NEW_CATEGORY_TO_FALSE';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const RESET_STATE_REMOVE_CATEGORY = "RESET_STATE_REMOVE_CATEGORY";
export const CHANGE_CATEGORY_NAME = 'CHANGE_CATEGORY_NAME';
export const RESET_STATE_CHANGE_CATEGORY = 'RESET_STATE_CHANGE_CATEGORY';
