/**
 * Created by vuchien on 6/21/16.
 */
export const FETCHING_DETAIL = 'FETCHING_DETAIL';
export const RECEIVE_DETAIL = 'RECEIVE_DETAIL';
export const ONCHANGE_CATEGORY_NAME = 'ONCHANGE_CATEGORY_NAME';
export const SHOW_FORM_UPDATE_CATEGORY = 'SHOW_FORM_UPDATE_CATEGORY';
export const HIDE_FORM_UPDATE_CATEGORY = 'HIDE_FORM_UPDATE_CATEGORY';
export const ADD_NEW_ATTRIBUTE_OPTION = 'ADD_NEW_ATTRIBUTE_OPTION';
export const CREATE_OR_UPDATE_ATTRIBUTE = 'CREATE_OR_UPDATE_ATTRIBUTE';
export const RECEIVE_DETAIL_ATTRIBUTE = 'RECEIVE_DETAIL_ATTRIBUTE';
export const UPDATE_STATUS_FETCH_DETAIL_TO_FALSE = 'UPDATE_STATUS_FETCH_DETAIL_TO_FALSE';
export const RESET_ATTRIBUTE_FORM = 'RESET_ATTRIBUTE_FORM';
export const SAVE_OR_UPDATE_ATTRIBUTE_IS_FINISHED_TO_FALSE = 'SAVE_OR_UPDATE_ATTRIBUTE_IS_FINISHED_TO_FALSE';
export const UPDATE_RECEIVED_TO_FALSE = 'UPDATE_RECEIVED_TO_FALSE';
