/**
 * Created by vuchien on 7/5/16.
 */
export const IS_FETCHING_LIST_PRODUCTS = 'IS_FETCHING_LIST_PRODUCTS';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS = 'PREVIOUS';
export const SEARCH_RECEIVE = 'SEARCH_RECEIVE';
export const RESET_DETAIL_PRODUCT = 'RESET_DETAIL_PRODUCT';
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const RESET_STATE_REMOVE_PRODUCT = "RESET_STATE_REMOVE_PRODUCT";
export const CHANGE_PRODUCT_NAME = 'CHANGE_PRODUCT_NAME';
export const RESET_STATE_CHANGE_PRODUCT = 'RESET_STATE_CHANGE_PRODUCT';
