/**
 * Created by vuchien on 8/13/16.
 */

/* Row events */
export const ADD_ROW = 'ADD_ROW';

/* Component events */
export const INSERT_COMPONENT = 'INSERT_COMPONENT';
export const UP_DOWN_INDEX = 'UP_DOWN_INDEX';
export const UPDATE_RAW_ITEM = 'UPDATE_RAW_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const IS_UP_DOWN_SUCCESS = 'IS_UP_DOWN_SUCCESS';
export const SAVE_IMAGE_PATH_UPLOAD_COMPONENT = 'SAVE_IMAGE_PATH_UPLOAD_COMPONENT';
export const IS_UPDATE_HIDDEN_IMAGE_UPLOAD_FOR_IMAGE_COMPONENT_TO_FALSE = 'IS_UPDATE_HIDDEN_IMAGE_UPLOAD_FOR_IMAGE_COMPONENT_TO_FALSE';

/* Something else */
export const RECEIVED_PRODUCT_DETAIL_DESIGN_FOR_EDIT = 'RECEIVED_PRODUCT_DETAIL_DESIGN_FOR_EDIT';
export const SAVE_PRODUCT_DESIGN_SUCCESS = 'SAVE_PRODUCT_DESIGN_SUCCESS';
export const UPDATE_PRODUCT_SUCCESS_TO_FALSE = 'UPDATE_PRODUCT_SUCCESS_TO_FALSE';
export const IS_SAVE_HANDLING_TO_TRUE = 'IS_SAVE_HANDLING_TO_TRUE';
export const IS_FETCHING_DATA_FOR_EDIT = 'IS_FETCHING_DATA_FOR_EDIT';
export const UPDATE_FETCHING_AND_FETCHED_STATUS_TO_FALSE = 'UPDATE_FETCHING_AND_FETCHED_STATUS_TO_FALSE';
export const IS_UPDATE_CALLING_USED_TEMP_PRODUCT_ID_TO_FALSE = 'IS_UPDATE_CALLING_USED_TEMP_PRODUCT_ID_TO_FALSE';

export const SHOW_UPLOAD_IMAGE_FOR_IMAGE_COMPONENT = 'SHOW_UPLOAD_IMAGE_FOR_IMAGE_COMPONENT';
export const SHOW_UPLOAD_IMAGE_FOR_IMAGE_COMPONENT_TO_FALSE = 'SHOW_UPLOAD_IMAGE_FOR_IMAGE_COMPONENT_TO_FALSE';

/* Row events */
export const ROW_MOVE_UP_DOWN = 'ROW_MOVE_UP_DOWN';
export const REMOVE_ROW = 'REMOVE_ROW';

/* Column event */
export const REMOVE_COLUMN = 'REMOVE_COLUMN';

export const STYLE_THREE_COLUMN = 3;
export const STYLE_TWO_COLUMN = 2;
export const STYLE_ONE_COLUMN = 1;

export const COMPONENT_TITLE_TEXT = 'COMPONENT_TEXT';
export const COMPONENT_PARAGRAPH = 'COMPONENT_PARAGRAPH';
export const COMPONENT_IMAGE = 'COMPONENT_IMAGE';
