/**
 * Created by vuchien on 7/19/16.
 */

export const RECEIVE_PRODUCT_DETAIL = 'RECEIVE_PRODUCT_DETAIL';
export const CREATE_OR_UPDATE_PRODUCT_INFO = 'CREATE_OR_UPDATE_PRODUCT_INFO';
export const REMOVE_ITEM_LIST_IMAGE = 'REMOVE_ITEM_LIST_IMAGE';
export const REMOVE_HIGHLIGHT_INFO_ITEM = 'REMOVE_HIGHLIGHT_INFO_ITEM';
export const ADD_ITEM_INFO_HIGHLIGHT = 'ADD_ITEM_INFO_HIGHLIGHT';
export const RESET_EDIT_INFO_PRODUCT = 'RESET_EDIT_INFO_PRODUCT';
export const UPDATE_DETAIL_UPLOAD_COPY = 'UPDATE_DETAIL_UPLOAD_COPY';
export const SAVE_UPLOAD_PRODUCT_IMAGE = 'SAVE_UPLOAD_PRODUCT_IMAGE';
export const CHANGE_PRODUCT_SELECT_BY_INDEX_DETAIL = 'CHANGE_PRODUCT_SELECT_BY_INDEX_DETAIL';
export const CHANGE_PRODUCT_SELECT_BY_INDEX_DETAIL_COPY = 'CHANGE_PRODUCT_SELECT_BY_INDEX_DETAIL_COPY';

/* Set new productId to object detail and detailCopy with add new product type */
export const IS_NEW_PRODUCT_INSERTED = 'IS_NEW_PRODUCT_INSERTED';
export const RESET_DETAIL_PRODUCT = 'RESET_DETAIL_PRODUCT';

export const IS_FETCHING_PRODUCT_DETAIL = 'IS_FETCHING_PRODUCT_DETAIL';
export const IS_UPDATE_PRODUCT_INFO_TO_FALSE = 'IS_UPDATE_PRODUCT_INFO_TO_FALSE'; // UPDATED STATUS
export const IS_UPDATING_PRODUCT_INFO_TO_TRUE = 'IS_UPDATING_PRODUCT_INFO_TO_TRUE';
export const IS_LOADING_DETAIL_UPLOAD_TO_TRUE = 'IS_LOADING_DETAIL_UPLOAD_TO_TRUE';
export const IS_LOADING_DETAIL_UPLOAD_TO_FALSE = 'IS_LOADING_DETAIL_UPLOAD_TO_FALSE';
export const UPDATE_IS_APPEND_NEW_ITEM_TO_LIST_IMAGE_DETAIL_COPY_TO_FALSE_PREVIEW_ZONE = 'UPDATE_IS_APPEND_NEW_ITEM_TO_LIST_IMAGE_DETAIL_COPY_TO_FALSE_PREVIEW_ZONE';
export const UPDATE_IS_ADDED_NEW_ITEM_TO_LIST_IMAGE_DETAIL_COPY_TO_FALSE = 'UPDATE_IS_ADDED_NEW_ITEM_TO_LIST_IMAGE_DETAIL_COPY_TO_FALSE';


// Detail product attributes
export const RECEIVE_DETAIL_PRODUCT_ATTRIBUTE = 'RECEIVE_DETAIL_PRODUCT_ATTRIBUTE';
export const UPDATE_DETAIL_ATTRIBUTE_PRODUCT_TO_FALSE = 'UPDATE_DETAIL_ATTRIBUTE_PRODUCT_TO_FALSE';
export const RECEIVE_ATTRIBUTES_BY_CATE_ONCHANGE = 'RECEIVE_ATTRIBUTES_BY_CATE_ONCHANGE';
export const UPDATE_IS_FETCHING_ATTRIBUTES_BY_CATE_ID_TO_TRUE = 'UPDATE_IS_FETCHING_ATTRIBUTES_BY_CATE_ID_TO_TRUE'; // isFetchingAttributesByChangeCateId
export const UPDATE_ATTRIBUTE_OPTION_BY_ATTRIBUTE_ID = 'UPDATE_ATTRIBUTE_OPTION_BY_ATTRIBUTE_ID';
export const UPDATE_IS_LOADING_HANDLE_SAVE_TO_TRUE = 'UPDATE_IS_LOADING_HANDLE_SAVE_TO_TRUE';
export const UPDATE_ATTRIBUTE_FINISHED = 'UPDATE_ATTRIBUTE_FINISHED';
export const UPDATE_IS_SAVED_ATTRIBUTES_TO_FALSE = 'UPDATE_IS_SAVED_ATTRIBUTES_TO_FALSE';

// product design
export const RECEIVE_PRODUCT_DETAIL_DESIGN = 'RECEIVE_PRODUCT_DETAIL_DESIGN';
export const IS_RECEIVED_DETAIL_DESIGN_DATA = 'IS_RECEIVED_DETAIL_DESIGN_DATA';

// active tempProduct mode
export const ACTIVE_USED_TEMP_PRODUCT_MODE = 'ACTIVE_USED_TEMP_PRODUCT_MODE';
